// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module('FuApp', ['ngAnimate', 'ngRoute']);

  app.controller('FuAppCtrl', function($interval) {
    this.temp = "Hello";
  });

}).call(this);

//# sourceMappingURL=app.map
