// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module('FuApp', ['ngAnimate', 'ngRoute']);

  app.config(function($routeProvider, $locationProvider) {
    return $routeProvider.when('/', {
      templateUrl: 'partials/home.html'
    }).when('/profile', {
      templateUrl: 'partials/profile.html'
    }).when('/about', {
      templateUrl: 'partials/about.html'
    }).when('/share', {
      templateUrl: 'partials/share.html',
      controller: "ShareCtrl",
      controllerAs: "share"
    }).otherwise({
      redirectTo: '/'
    });
  });

  app.controller('FuAppCtrl', function($interval) {
    this.loggedIn = true;
  });

  app.controller('ShareCtrl', function() {
    this.temp = "hi";
  });

}).call(this);

//# sourceMappingURL=app.map
